resources:
  - name: start_all
    type: PropertyBag
    configuration:
      hello: world
  - name: bprepo
    type: GitRepo
    configuration:
      gitProvider: johns_bbs
      path: PIP/buildplane
      branches:
        include: ^feature-PIPE-5073$

pipelines:
  - name: pagerduty_notifications
    configuration:
      environmentVariables:
        readOnly:
          myRoutingKey: 8c22b13ccaa04da79a9952761248c337
    steps:
      - name: ps_pagerduty_success
        type: PowerShell
        configuration:
          nodePool: static-win
          inputResources:
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - try { send_notification pagerduty -routingkey $myRoutingKey -text "hello world from powershell run number $run_number" } catch { $_ }
            - try { send_notification pagerduty -routingkey $myRoutingKey } catch { $_ }
            - try { send_notification pagerduty -routingkey badkey -text "bad routing key" } catch { $_ }
            - try { send_notification pagerduty -text "no routing key" } catch { $_ }
            - try { send_notification pagerduty } catch { $_ }

      - name: bash_pagerduty_success
        type: Bash
        configuration:
          inputResources:
            - name: bprepo
            - name: start_all
          integrations:
            - name: pagerduty
        execution:
          onStart:
            - echo "starting"
          onExecute:
            - echo "$int_pagerduty_token"
            - pushd $res_bprepo_resourcePath
            - source core/execTemplates/steps/jfrog/v1.0/Bash/header.sh
            - send_notification pagerduty --text "hello world from bash run number $run_number"
            - send_notification pagerduty || true



      - name: bash_pagerduty_failure1
        type: Bash
        configuration:
          inputResources:
            - name: bprepo
            - name: start_all
          inputSteps:
            - name: bash_pagerduty_success
        execution:
          onExecute:
            - pushd $res_bprepo_resourcePath
            - source execTemplates/steps/jfrog/v1.0/Bash/header.sh
