template: true
valuesFilePath: ./values.yml

resources:
  - name: {{ .Values.namePrefix }}_repo
    type: GitRepo
    configuration:
      path: {{ .Values.repo.path }}
      gitProvider: {{ .Values.repo.gitIntegration }}
      branches:
        include: {{ .Values.repo.branchPattern | default "main" }}

  - name: {{ .Values.namePrefix }}_simpleserver
    type: GitRepo
    configuration:
      gitProvider: github
      path: trriplejay/simpleserver
      branches:
        include: "^master$"

  - name: {{ .Values.namePrefix }}_info
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}

  - name: {{ .Values.namePrefix }}_spec
    type: FileSpec
    configuration:
      sourceArtifactory: {{ .Values.artIntegration }}
      pattern: '{{ .Values.buildSpecPattern | default "*" }}'
      buildName: ${JFROG_CLI_BUILD_NAME}
      buildNumber: ${JFROG_CLI_BUILD_NUMBER}


pipelines:
  - name: {{ .Values.namePrefix }}_maven_ci_docker
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: build
        type: MvnBuild
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: ${pipeline_name}_maven
            JFROG_CLI_BUILD_NUMBER: ${run_id}
          integrations:
            - name: {{ .Values.artIntegration }}
          inputResources:
            - name: {{ .Values.namePrefix }}_repo
          outputResources:
            - name: {{ .Values.namePrefix }}_info
            - name: {{ .Values.namePrefix }}_spec
          autoPublishBuildInfo: true
        {{ if .Values.scanBuild }}
          forceXrayScan: true
        {{ end }}
        {{ if .Values.mavenConfig.command }}
          mvnCommand: {{ .Values.mavenConfig.command }}
        {{ end }}
        {{ if .Values.mavenConfig.sourceLocation }}
          sourceLocation: {{ .Values.mavenConfig.sourceLocation }}
        {{ end }}
        {{ if .Values.mavenConfig.resolverSnapshotRepo }}
          resolverSnapshotRepo: {{ .Values.mavenConfig.resolverSnapshotRepo }}
        {{ end }}
        {{ if .Values.mavenConfig.deployerSnapshotRepo }}
          deployerSnapshotRepo: {{ .Values.mavenConfig.deployerSnapshotRepo }}
        {{ end }}
        {{ if .Values.mavenConfig.resolverReleaseRepo }}
          resolverReleaseRepo: {{ .Values.mavenConfig.resolverReleaseRepo }}
        {{ end }}
        {{ if .Values.mavenConfig.deployerReleaseRepo }}
          deployerReleaseRepo: {{ .Values.mavenConfig.deployerReleaseRepo }}
        {{ end }}
      {{ if .Values.publishBuild }}
        execution:
          onSuccess:
            - write_output {{ .Values.namePrefix }}_spec buildName="${JFROG_CLI_BUILD_NAME}"
            - write_output {{ .Values.namePrefix }}_spec buildNumber="${JFROG_CLI_BUILD_NUMBER}"
      {{ end }}

      - name: build
        type: DockerBuild
        configuration:
          affinityGroup: docker
          dockerFileLocation: "."
          dockerFileName: Dockerfile
          dockerImageName: {{ .Values.dockerConfig.imageName }}
          dockerImageTag: {{ .Values.dockerConfig.imageTag }}
          inputResources:
            - name: {{ .Values.namePrefix }}_simpleserver
            - name: {{ .Values.namePrefix }}_spec
              trigger: false
          integrations:
            - name: {{ .Values.artIntegration }}

      - name: push
        type: DockerPush
        configuration:
          affinityGroup: docker
          inputSteps:
            - name: build
          integrations:
            - name: {{ .Values.artIntegration }}
