pipelines:
  - name: mypip_johns
    steps:
      - name: bashtest
        type: Bash
        configuration:
          nodePool: k8s
          runtime:
            type: host
        execution:
          onExecute:
            - echo "hello"
            - docker run hello-world
            - docker images
            - docker info
            - docker ps -a
            # - cat /etc/drydock/.env
            - echo "$REQEXEC_DIR"
            - echo "$REQKICK_DIR"
            - ls $REQKICK_DIR
            - ps -aux
            - systemctl status pipelines-reqKick
