resources:
  - name: examples_repo
    type: GitRepo
    configuration:
      path: ~johns/step_samples
      gitProvider: johns_bbs
      branches:
        include: master

pipelines:
  - name: MavenSamples
    steps:
      - name: BuildSample
        type: MvnBuild
        configuration:
          sourceLocation: projects/maven-example
          resolverSnapshotRepo: maven-jcenter
          resolverReleaseRepo: maven-jcenter
          deployerSnapshotRepo: maven-local
          deployerReleaseRepo: maven-local
          mvnCommand: "clean install"
          inputResources:
            - name: examples_repo
          integrations:
            - name: johns_art
        execution:
          onStart:
            - docker ps -a