resources:
- name: auto_git
  type: GitRepo
  configuration:
    gitProvider: johns_gh
    path: trriplejay/Org_test_Automation
    branches:
      include: ^master$

pipelines:
  - name: test_files
    steps:
      - name: bash_files_add
        type: Bash
        configuration:

          inputResources:
            - name: auto_git
        execution:
          onExecute:
            - add_run_files $res_auto_git_resourcePath bashrepo
      - name: bash_files_restore
        type: Bash
        configuration:
          inputSteps:
            - name: bash_files_add
        execution:
          onExecute:
            - restore_run_files bashrepo repocontents

      - name: powershell_files_add
        type: PowerShell
        configuration:
          inputResources:
            - name: auto_git
        execution:
          onExecute:
            - add_run_files $res_auto_git_resourcePath psrepo

      - name: powershell_files_restore
        type: PowerShell
        configuration:

          inputSteps:
            - name: powershell_files_add
        execution:
          onExecute:
            - restore_run_files psrepo repocontents





      - name: bash_files_prematrix
        type: PreMatrix
        configuration:
          nodePool: u16dynamic
          inputResources:
            - name: auto_git
        execution:
          onExecute:
            - pushd $res_auto_git_resourcePath
            - cat "hello world" > hello.txt
            - echo "done"

      - name: bash_files_matrix_multi
        type: Matrix
        configuration:
          multiNode: true
          nodePool: u16dynamic
          inputSteps:
            - name: bash_files_prematrix
        stepletMultipliers:
          environmentVariables:
            - foo: bar
            - foo: hello
        execution:
          onExecute:
            - printenv
            - echo "hello"


      - name: bash_files_postmatrix
        type: PostMatrix
        configuration:
          nodePool: u16dynamic
          inputSteps:
            - name: bash_files_matrix_multi

      - name: bash_files_matrix_single
        type: Matrix
        configuration:
          nodePool: u16dynamic
          inputResources:
            - name: auto_git
        stepletMultipliers:
          environmentVariables:
            - foo: bar
            - foo: hello
        execution:
          onExecute:
            - echo "hello"