resources:
- name: auto_git
  type: GitRepo
  configuration:
    gitProvider: github
    path: trriplejay/Org_test_Automation
    branches:
      include: ^master$

pipelines:
  - name: test_files
    steps:
      - name: bash_files_add
        type: Bash
        configuration:

          inputResources:
            - name: auto_git
        execution:
          onExecute:
            - add_run_files $res_auto_git_resourcePath bashrepo
      - name: bash_files_restore
        type: Bash
        configuration:
          inputSteps:
            - name: bash_files_add
        execution:
          onExecute:
            - restore_run_files bashrepo repocontents

      - name: powershell_files_add
        type: PowerShell
        configuration:
          inputResources:
            - name: auto_git
        execution:
          onExecute:
            - add_run_files $res_auto_git_resourcePath psrepo

      - name: powershell_files_restore
        type: PowerShell
        configuration:

          inputSteps:
            - name: powershell_files_add
        execution:
          onExecute:
            - restore_run_files psrepo repocontents





      - name: bash_files_prematrix
        type: PreMatrix
        configuration:
          inputResources:
            - name: auto_git
        execution:
          onExecute:
            - echo "this adds the cloned GitRepo to matrix state"
            - echo "so that it doesnt need to be cloned in every matrix steplet"
            - echo "done"


      - name: bash_files_matrix_multi
        type: Matrix
        configuration:
          multiNode: true
          inputSteps:
            - name: bash_files_prematrix
        stepletMultipliers:
          environmentVariables:
            - foo: bar
            - foo: hello
        execution:
          onExecute:
            - export repoPath="bash_files_prematrix/dependencyState/resources/auto_git"
            - pushd $repoPath
            - ls -latr
            - popd
            - echo "building my app" > app_${foo}.txt


      - name: bash_files_postmatrix
        type: PostMatrix
        configuration:
          inputSteps:
            - name: bash_files_matrix_multi
        execution:
          onExecute:
            - echo "hello"
            - cd bash_files_matrix_multi
            - ls -latr

      - name: bash_files_matrix_single
        type: Matrix
        configuration:
          inputResources:
            - name: auto_git
        stepletMultipliers:
          environmentVariables:
            - foo: bar
            - foo: hello
        execution:
          onExecute:
            - echo "hello"