resources:
  - name: simple_git
    type: GitRepo
    configuration:
      gitProvider: github
      path: trriplejay/simpleserver
      branches:
        include: ^master$
      buildOn:
        releaseCreate: true
      buildOn:
        commit: false

pipelines:
  - name: test_release
    steps:
      - name: my_release
        type: Bash
        configuration:
          inputResources:
            - name: simple_git
        execution:
          onExecute:
            - printenv | grep simple_git
            - echo "done"
  - name: john_run_state_functions
    steps:
      - name: setup_state
        type: Bash
        configuration:
          integrations:
            - name: art
        execution:
          onExecute:
            - jfrog rt dl data-dump/test-data.tar.gz
            - ls -latr
            - add_run_files test-data.tar.gz testdata

      - name: no_state
        type: Bash
        configuration:
          inputSteps:
            - name: setup_state
        execution:
          onExecute:
            - echo "no state used here"

      - name: use_state
        type: Bash
        configuration:
          inputSteps:
            - name: no_state
        execution:
          onExecute:
            - echo "about to load state"
            - restore_run_files testdata test-data.tar.gz
            - ls -latr


