resources:
  - name: johns_bbs_repo
    type: GitRepo
    configuration:
       gitProvider: johns_bbs
       path: ~johns/simpleserver

pipelines:
  - name: johns_clone_test
    steps:
      - name: johns_clone_step
        type: Bash
        configuration:
          inputResources:
            - name: johns_bbs_repo
        execution:
          onExecute:
            - cd $res_johns_bbs_repo_resourcePath
            - ls -latr