resources:
  - name: dummy
    type: PropertyBag
    configuration:
      foo: bar
  - name: johns_gh_repo
    type: GitRepo
    configuration:
       gitProvider: johns_gh
       path: trriplejay/simpleserver

pipelines:
  - name: johns_gh_clone_test
    steps:
      - name: johns_gh_clone_step
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-u18node
                tag: "12.18.2"
                autoPull: true
          inputResources:
            - name: dummy
            - name: johns_gh_repo
        execution:
          onExecute:
            - pushd $res_johns_gh_repo_resourcePath
            - git version
            - ls -latrR
            - docker ps -a
            - docker inspect step-$step_id-$steplet_id || true
            # - pushd dependencyState
            # - git clone https://github.com/trriplejay/simpleserver.git "../dependencyState"
            # - ls -latrR
      - name: long_clone
        type: Bash
        configuration:
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - |
                mydir="test${step_id}"
                mkdir $mydir
                pushd $mydir
                gitCloneCmd="git clone https://github.com/trriplejay/simpleserver.git ../$mydir"
                echo "about to clone"
                retry_command $gitCloneCmd
                echo "about to config user.name"
                git config --get user.name || git config user.name 'JFrog Pipelines Step'
                echo "about to config user.email"
                git config --get user.email || git config user.email 'build@pipelines.jfrog.com'
                echo "about to checkout"
                git checkout HEAD^
                echo "done checking out"






