resources:
  - name: johns_gh_repo
    type: GitRepo
    configuration:
       gitProvider: johns_gh
       path: trriplejay/simpleserver

pipelines:
  - name: johns_gh_clone_test
    steps:
      - name: johns_gh_clone_step
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: releases-docker.jfrog.io/jfrog/pipelines-u18node
                tag: 14
                autoPull: true
          inputResources:
            - name: johns_gh_repo
        execution:
          onExecute:
            - pushd $res_johns_gh_repo_resourcePath
            - ls -latrR
            - docker ps -a
            - docker inspect step-$step_id-$steplet_id || true
            # - pushd dependencyState
            # - git clone https://github.com/trriplejay/simpleserver.git "../dependencyState"
            # - ls -latrR



