resources:
  - name: johns_gh_repo
    type: GitRepo
    configuration:
       gitProvider: johns_gh
       path: trriplejay/simpleserver

pipelines:
  - name: johns_gh_clone_test
    steps:
      - name: johns_gh_clone_step
        type: Bash
        # configuration:
        #   inputResources:
        #     - name: johns_gh_repo
        execution:
          onExecute:
            # - cd $res_johns_gh_repo_resourcePath
            - ls -latrR
            - docker ps -a
            - docker inspect step-$step_id-$steplet_id || true
            - git clone https://github.com/trriplejay/simpleserver.git "$(pwd)/dependencyState"
            - ls -latrR
            - rm -rf dependencyState/*
            - cd dependencyState
            - git clone https://github.com/trriplejay/simpleserver.git "../dependencyState"
            - ls -latrR



