resources:
  - name: dummy
    type: PropertyBag
    configuration:
      foo: bar
  - name: johns_gh_repo
    type: GitRepo
    configuration:
      gitProvider: johns_gh
      path: trriplejay/simpleserver
      branches:
        include: ^master$
      files:
        include: .*


pipelines:
  - name: johns_gh_clone_test
    steps:
      - name: johns_gh_clone_step
        type: Bash
        configuration:
          inputResources:
            - name: dummy
            - name: johns_gh_repo
        execution:
          onExecute:
            - pushd $res_johns_gh_repo_resourcePath
            - git version
            - ls -latrR
            - printenv | grep res_johns_gh
            - echo "$(get_resource_names --type GitRepo)"
            - echo "$(get_resource_name --type GitRepo)"
            - echo "$(get_resource_variable johns_gh_repo branches_include"

      - name: long_clone
        type: Bash
        configuration:
          inputResources:
            - name: dummy
        execution:
          onExecute:
            - |
                mydir="test${step_id}"
                mkdir $mydir
                pushd $mydir
                gitCloneCmd="git clone https://github.com/trriplejay/simpleserver.git ../$mydir"
                echo "about to clone"
                retry_command $gitCloneCmd
                echo "about to config user.name"
                git config --get user.name || git config user.name 'JFrog Pipelines Step'
                echo "about to config user.email"
                git config --get user.email || git config user.email 'build@pipelines.jfrog.com'
                echo "about to checkout"
                git checkout HEAD^
                echo "done checking out"






