resources:
  # - name: singleRepo_simple
  #   type: GitRepo
  #   configuration:
  #     gitProvider: johns_github
  #     path: trriplejay/simpleserver
  #     branches:
  #       include: master

  - name: myProps
    type: PropertyBag
    configuration:
      foo: bar
      hello: world

  - name: startingProps
    type: PropertyBag
    configuration:
      fileprefix: "tomcat"
      not: again
  - name: testProps
    type: propertyBag
    configuration:
      zero_run_number_copy: ${res_startingProps_zero_run_number}
      zero_run_number_copy2: ${zero_run_number}


pipelines:
  - name: johns_simple_pipe_simple_gh
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          timeoutSeconds: 100000
          environmentVariables:
            releaseBundleName: mybundlename
            releaseBundleVersion: mybundleversion
          integrations:
            - name: johns_github
          inputResources:
            - name: startingProps
            - name: testProps
            # - name: testSpec
          #   - name: singleRepo_simple
          outputResources:
            - name: myProps
        execution:
          onStart:
            - docker ps -a
            - docker images
            - resource_directory=$(find_resource_variable "myProps" resourcePath)
            - env_file_path="$resource_directory/myProps.env"
            - echo "name=$(find_step_configuration_value releaseBundleName)" >> $env_file_path
            - echo "version=$(find_step_configuration_value releaseBundleVersion)" >> $env_file_path

            - cat $env_file_path
