
pipelines:
  - name: johns_simple_pipe_simple_gh
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          nodePool: test_disk_size
        execution:
          onStart:
            - echo "test"
            - df -h
