pipelines:
  - name: johns_S_Matrix_0059
    steps:
      - name: S_Matrix_0059
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          fastFail: true
          environmentVariables:
            - delay: 1
              fail: 'true'
            - delay: 2
              fail: 'true'
            - delay: 3
              fail: 'false'
            - delay: 5
              fail: 'false'
        execution:
          onStart:
            - sleep "$delay"
          onExecute:
            - echo "I am on matrix step"
            - |
              [ $fail == 'false' ]
            - ls -l .



  - name: johns_S_Matrix_0060
    steps:
      - name: S_Matrix_0060
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          fastFail: true
          environmentVariables:
            - delay: 1
              fail: 'false'
            - delay: 2
              fail: 'false'
            - delay: 3
              fail: 'true'
            - delay: 5
              fail: 'false'
        execution:
          onStart:
            - sleep "$delay"
          onExecute:
            - echo "I am on matrix step"
            - |
              [ $fail == 'false' ]
            - ls -l .
