resources:
  - name: myGitRepo
    type: GitRepo
    configuration:
      path: ~johns/simpleserver
      gitProvider: johns_bbs
      branches:
        include: ^master$


pipelines:
  - name: my_upload_test
    steps:
      - name: upload_rt
        type: jfrog_dev/UploadArtifact
        configuration:
          integrations:
            - name: main_rt
          inputResources:
            - name: myGitRepo
          sourcePath: $res_myGitRepo_resourcePath/*
          targetPath: testupload/simpleserver

