resources:
  - name: build1
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
  - name: build2
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
  - name: build3
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
  - name: build_final
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory



pipelines:
  - name: test_builds
    environmentVariables:
      readOnly:
        serviceRepo: servicefiles
    steps:
      - name: service1
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: service_1_build
          integrations:
            - name: artifactory
          outputResources:
            - name: build1
        execution:
          onExecute:
            - echo "hello service1" > svc1.txt
            - jfrog rt u svc1.txt ${serviceRepo}/service1/svc1.txt
            - jfrog rt bce
            - jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - write_output build1 "$JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NUMBER"

      - name: service2
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: service_2_build
          integrations:
            - name: artifactory
          outputResources:
            - name: build2
        execution:
          onExecute:
            - echo "hello service2" > svc2.txt
            - jfrog rt u svc2.txt ${serviceRepo}/service2/svc2.txt
            - jfrog rt bce
            - jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - write_output build2 "$JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NUMBER"

      - name: service3
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: service_3_build
          integrations:
            - name: artifactory
          outputResources:
            - name: build3
        execution:
          onExecute:
            - echo "hello service3" > svc3.txt
            - jfrog rt u svc3.txt ${serviceRepo}/service3/svc3.txt
            - jfrog rt bce
            - jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - write_output build3 "$JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NUMBER"
      - name: aggregate
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: aggregate_build
          inputResources:
            - name: build1
            - name: build2
            - name: build3
          outputResources:
            - name: build_final

        execution:
          onExecute:
            - jfrog rt build-append $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER ${res_build1_buildName} ${res_build1_buildNumber}
            - jfrog rt build-append $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER ${res_build2_buildName} ${res_build2_buildNumber}
            - jfrog rt build-append $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER ${res_build3_buildName} ${res_build3_buildNumber}
            - jfrog rt build-publish $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER