resources:
  - name: build1
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
  - name: build2
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
  - name: build3
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
  - name: build_final
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
  - name: app_repo
    type: GitRepo
    configuration:
      gitProvider: github
      path: trriplejay/simpleserver
      branches:
        include: ^master$



pipelines:
  - name: test_builds
    configuration:
      environmentVariables:
        readOnly:
          serviceRepo: servicefiles
    steps:
      - name: service1
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: service_1_build
          integrations:
            - name: artifactory
          inputResources:
            - name: app_repo
          outputResources:
            - name: build1
        execution:
          onExecute:
            - pushd $res_app_repo_resourcePath
            - docker build -t https://swampup303.jfrog.io/docker-all/servicea:${JFROG_CLI_BUILD_NUMBER} .
            - jfrog rt docker-push https://swampup303.jfrog.io/docker-all/servicea:${run_number} docker-all --build-name=JFROG_CLI_BUILD_NAME --build-number $JFROG_CLI_BUILD_NUMBER
            - jfrog rt bce $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - jfrog rt bag $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - write_output build1 "buildName=$JFROG_CLI_BUILD_NAME" "buildNumber=$JFROG_CLI_BUILD_NUMBER"

      - name: service2
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: service_2_build
          integrations:
            - name: artifactory
          outputResources:
            - name: build2
        execution:
          onExecute:
            - echo "hello service2" > svc2.txt
            - jfrog rt u svc2.txt ${serviceRepo}/service2/svc2.txt
            - jfrog rt bce
            - jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - write_output build2 "buildName=$JFROG_CLI_BUILD_NAME" "buildNumber=$JFROG_CLI_BUILD_NUMBER"

      - name: service3
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: service_3_build
          integrations:
            - name: artifactory
          outputResources:
            - name: build3
        execution:
          onExecute:
            - echo "hello service3" > svc3.txt
            - jfrog rt u svc3.txt ${serviceRepo}/service3/svc3.txt
            - jfrog rt bce
            - jfrog rt bp $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER
            - write_output build3 "buildName=$JFROG_CLI_BUILD_NAME" "buildNumber=$JFROG_CLI_BUILD_NUMBER"
      - name: aggregate
        type: Bash
        configuration:
          environmentVariables:
            JFROG_CLI_BUILD_NAME: aggregate_build
          integrations:
            - name: artifactory
          inputResources:
            - name: build1
            - name: build2
            - name: build3
          outputResources:
            - name: build_final

        execution:
          onExecute:
            - jfrog rt build-append $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER ${res_build1_buildName} ${res_build1_buildNumber}
            - jfrog rt build-append $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER ${res_build2_buildName} ${res_build2_buildNumber}
            - jfrog rt build-append $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER ${res_build3_buildName} ${res_build3_buildNumber}
            - jfrog rt build-publish $JFROG_CLI_BUILD_NAME $JFROG_CLI_BUILD_NUMBER