pipelines:
  - name: johns_approval
    steps:
      - name: first_step
        type: Bash
        execution:
          onExecute:
            - echo "starting"
      - name: approval_step
        type: Bash
        configuration:
          inputSteps:
            - name: first_step
          requiresApproval:
            approvers:
              - johns
        execution:
          onExecute:
            - echo "i've been approved!"
      - name: last_step
        type: Bash
        configuration:
          inputSteps:
            - name: approval_step
        execution:
          onExecute:
            - echo "i'm done"