template: true
valuesFilePath: ../values.yml

resources:
  - name: {{ .Values.prefix }}_image
    type: Image
    configuration:
      registry: {{ .Values.rtInt }}
      imageName: johnsdemo.jfrogdev.org/docker-dev-local/simpleserver
      sourceRepository: docker-dev-local
      imageTag: ${run_id}

  - name: {{ .Values.prefix }}_repo
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.ghInt }}
      path: trriplejay/simpleserver


pipelines:
  - name: {{ .Values.prefix }}_cliv2_pipe
    configuration:
      jfrogCliVersion: 2
      integrations:
        - name: {{ .Values.rtInt }}
    steps:
      - name: {{ .Values.prefix }}_build
        type: DockerBuild
        configuration:
          inputResources:
            - name: {{ .Values.prefix }}_repo
          affinityGroup: docker
          dockerImageName: johnsdemo.jfrogdev.org/docker-dev-local/simpleserver
          dockerImageTag: "$run_id"
          dockerOptions: --pull --no-cache

      - name: {{ .Values.prefix }}_test
        type: Bash
        configuration:
          affinityGroup: docker
          inputSteps:
            - name: {{ .Values.prefix }}_build
        execution:
          onExecute:
            - jfrog --version
            - docker images

      - name: {{ .Values.prefix }}_push
        type: DockerPush
        configuration:
          affinityGroup: docker
          targetRepository: dev-docker-local
          inputSteps:
            - name: {{ .Values.prefix }}_test
          outputResources:
            - name: {{ .Values.prefix }}_image
