resources:
  - name: signed_git
    type: GitRepo
    configuration:
      scmProvider: johns_bbs
      path: ~johns/simpleserver
      branches:
        include: ^master$

  - name: signed_buildinfo
    type: BuildInfo
    configuration:
      sourceArtifactory: johns_art

pipelines:
  - name: test_signed_start
    steps:
      - name: create_info
        type: Bash
        configuration:
          inputResources:
            - name: signed_git
          integrations:
            - name: johns_art
          outputResources:
            - name: signed_buildinfo
        execution:
          onExecute:
            - cd $res_signed_git_resourcePath
            - jfrog rt upload server.js
            - jfrog rt build-collect-environment
            - jfrog rt build-publish --build-name=$JFROG_CLI_BUILD_NAME --build-number=$JFROG_CLI_BUILD_NUMBER
            - save_artifact_info signed_buildinfo
  - name: test_signed_stop
    steps:
      - name: validate_info
        type: Bash
        configuration:
          inputResources:
            - name: signed_buildinfo
        execution:
          onExecute:
            - response=$(validate_artifact signed_buildinfo ${signed_buildinfo_buildName} ${signed_buildinfo_buildNumber})

