resources:
  - name: utilRepo
    type: GitRepo
    configuration:
      path: trriplejay/step_samples
      gitProvider: github
      branches:
        include: ^master$
  - name: settings_bag
    type: PropertyBag
    configuration:
      date: ""
      run_id: ""

pipelines:
  - name: test_exports
    steps:
      - name: exports
        type: Bash
        configuration:
          inputResources:
            - name: utilRepo
          outputResources:
            - name: settings_bag
        execution:
          onExecute:
            - echo "run the script"
            - pushd $res_utilRepo_resourcePath
            - cat testscript.sh
            - ./testscript.sh