resources:
  - name: utilRepo
    type: GitRepo
    configuration:
      path: trriplejay/step_samples
      gitProvider: github
      branches:
        include: ^master$

pipelines:
  - name: test_exports
    steps:
      - name: exports
        type: Bash
        configuration:
          inputResources:
            - name: utilRepo
        execution:
          onExecute:
            - echo "run the script"
            - pushd $res_utilRepo_resourcePath
            - cat testscript.sh
            - ./testscript.sh