resources:
  - name: dummy
    type: PropertyBag
    configuration:
      dummy: dummy
pipelines:
  - name: john_basic_sigterm
    steps:
      - name: step_sigterm
        type: Bash
        configuration:
          inputResources:
            - name: dummy
        execution:
          onStart:
            - set -x
            - echo "Setting everything up"
            - printenv | grep handle_sigterm
          onExecute:
            - echo "lets loop for a bit"
            - |
                local i=0
                while [[ $i -lt 1000 ]]; do
                  echo "total wait time: $i seconds";
                  sleep 1
                  i=$(($i + 1))
                done
            - echo "waiting complete. moving to success"
          onSuccess:
            - echo "we made it to success"
          onFailure:
            - echo "darn, we failed"
          onComplete:
            - echo "doing some cleanup in the onComplete section"
      - name: timeout_step_sigterm
        type: Bash
        configuration:
          timeoutSeconds: 5
          inputResources:
            - name: dummy
        execution:
          onStart:
            - set -x
            - echo "Setting everything up"
            - printenv | grep handle_sigterm
          onExecute:
            - echo "lets loop for a bit"
            - |
                local i=0
                while [[ $i -lt 1000 ]]; do
                  echo "total wait time: $i seconds";
                  sleep 1
                  i=$(($i + 1))
                done
            - echo "waiting complete. moving to success"
          onSuccess:
            - echo "we made it to success"
          onFailure:
            - echo "darn, we failed"
          onComplete:
            - echo "doing some cleanup in the onComplete section"