resources:
  - name: johns_cache_sample
    type: GitRepo
    configuration:
      gitProvider: github
      path: trriplejay/step_samples
      branches:
        include: ^master$

pipelines:
  - name: step_cache_test_johns
    steps:
    - name: step_cache_test
      type: Bash
      configuration:
        inputResources:
          - name: johns_cache_sample
      execution:
        onExecute:
          - mkdir -p /tmp/repo
          - ls -latr /tmp/repo
          - touch test.txt
          - add_cache_files test.txt repo
          # - ls -latr $res_johns_cache_sample
          # - restore_cache_files repo2 /tmp/repo
          # - ls -latr /tmp/repo
          # - ls -latr $res_johns_cache_sample
          # - cp -r $res_johns_cache_sample_resourcePath/* /tmp/repo
          # - ls -latr /tmp/repo
          # - ls -latr $res_johns_cache_sample
          # - cp -r /tmp/repo/* $res_johns_cache_sample_resourcePath
          # - ls -latr /tmp/repo
          # - ls -latr $res_johns_cache_sample
          # - add_cache_files $res_johns_cache_sample_resourcePath repo2
          # - ls -latr /tmp/repo
          # - ls -latr $res_johns_cache_sample

