resources:
  - name: eventframework_code_repo
    type: GitRepo
    configuration:
      gitProvider: github # name of the integration
      path: trriplejay/step_samples # temp so that pipeline sync will work
      branches:
        include: ^master$

  - name: docker_image_event_webhook_service
    type: Image
    configuration:
      registry: Creds_DockerRegistry_Punchh
      imageName: punchh/eventwebhook
      imageTag: latest

pipelines:
  - name: event_framework_ci
    configuration:
      environmentVariables:
        readOnly:
          COMPOSE: dmVyc2lvbjogIjMuOCIKc2VydmljZXM6CgogIG1vbmdvOgogICAgaW1hZ2U6IG1vbmdvCiAgICByZXN0YXJ0OiBhbHdheXMKICAgIGVudmlyb25tZW50OgogICAgICBNT05HT19JTklUREJfUk9PVF9VU0VSTkFNRTogcm9vdAogICAgICBNT05HT19JTklUREJfUk9PVF9QQVNTV09SRDogZXhhbXBsZQoKICBlczoKICAgIGltYWdlOiBkb2NrZXIuZWxhc3RpYy5jby9lbGFzdGljc2VhcmNoL2VsYXN0aWNzZWFyY2g6Ny4xMy40CiAgICBjb250YWluZXJfbmFtZTogZXMwMQogICAgZW52aXJvbm1lbnQ6CiAgICAgIC0gZGlzY292ZXJ5LnR5cGU9c2luZ2xlLW5vZGUKICAgIHZvbHVtZXM6CiAgICAgIC0gZXNfZGF0YTovdXNyL3NoYXJlL2VsYXN0aWNzZWFyY2gvZGF0YQogICAgcG9ydHM6CiAgICAgIC0gOTIwMDo5MjAwCiAgICAgIC0gOTMwMDo5MzAwCgogIHJlZGlzOgogICAgaW1hZ2U6IHJlZGlzCiAgICBwb3J0czoKICAgICAgLSAiNjM3OSIKICAgIHJlc3RhcnQ6IG9uLWZhaWx1cmUKICBkYjoKICAgIGltYWdlOiBteXNxbDo1LjcKICAgIHZvbHVtZXM6CiAgICAgIC0gZGJfZGF0YTovdmFyL2xpYi9teXNxbDpkZWxlZ2F0ZWQKICAgIHJlc3RhcnQ6IGFsd2F5cwogICAgZW52aXJvbm1lbnQ6CiAgICAgIE1ZU1FMX1JPT1RfUEFTU1dPUkQ6IHB1bmNoaDEyMwogICAgICBNWVNRTF9EQVRBQkFTRTogcHVuY2hoX2RldmVsb3BtZW50CiAgICAgIE1ZU1FMX1VTRVI6IGFwcF91c2VyCiAgICAgIE1ZU1FMX1BBU1NXT1JEOiBwdW5jaGgxMjMKICAgIHBvcnRzOgogICAgICAtICIzMzA2OjMzMDYiCgp2b2x1bWVzOgogIGRiX2RhdGE6CiAgZXNfZGF0YToK
          DOCKER_ACC: punchh
          DOCKER_REPO: eventwebhook
    steps:
      - name: event_framework_master_build
        type: Bash
        configuration:
          integrations:
            - name: Creds_DockerRegistry_Punchh
            - name: docker_image_slack_notification
            - name: EnvVars_Development_EventFramework
          inputResources:
            - name: eventframework_code_repo
          outputResources:
            - name: docker_image_event_webhook_service
        execution:
          onStart:
            # - echo $COMPOSE
            # - echo -n $COMPOSE
            - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            - sudo chmod +x /usr/local/bin/docker-compose
            - echo $COMPOSE | base64 --decode > docker-compose.yml
            - cat docker-compose.yml
            - docker-compose up -d
          onExecute:
            - echo "hello"
            - docker ps -a

          onSuccess:
            - |
                if ( [ $BRANCH == "master" ] && [ $IS_PULL_REQUEST == false ] )
                then
                  write_output docker_image_event_webhook_service "imageTag=$COMMIT buildNumber=$runNumber"
                fi

      - name: event_framework_staging_build
        type: Bash
        configuration:
          environmentVariables:
            PIPELINE_TRIGGER_DETAIL:
              description: "The branch you want to build"
              default: ""
              allowCustom: true
          integrations:
            - name: Creds_DockerRegistry_Punchh
            - name: docker_image_slack_notification
            - name: EnvVars_Development_EventFramework
          inputResources:
            - name: eventframework_code_repo
              trigger: false
            - name: docker_image_event_webhook_service
              trigger: false
        execution:
          onStart:
            - send_notification docker_image_slack_notification "started $step_name"
          onExecute:
            - export BRANCH_NAME="${int_EnvVars_Development_EventFramework_BRANCH_NAME}""
            - pushd ${res_eventframework_code_repo_resourcePath}
            - echo "step 2 branch name :- $BRANCH_NAME"
            - if [[ ${#PIPELINE_TRIGGER_DETAIL} -gt 0 ]]; then export BRANCH_NAME=$PIPELINE_TRIGGER_DETAIL; fi
            - git checkout $BRANCH_NAME
            - docker build -f app/build/Dockerfile -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH_NAME . --pull
            - docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH_NAME
          onComplete:
            - send_notification docker_image_slack_notification "finished $step_name"


