resources:
  - name: johns_devops_repo
    type: GitRepo
    configuration:
      gitProvider: github # name of the integration
      path: trriplejay/step_samples # temp so that pipeline sync will work
      branches:
        include: ^master$

  - name: johns_docker_image
    type: Image
    configuration:
      registry: Creds_DockerRegistry_Punchh
      imageName: punchh/eventwebhook
      imageTag: latest

pipelines:
  - name: johns_go_test
    configuration:
      environmentVariables:
        readOnly:

          DOCKER_ACC: punchh
          DOCKER_REPO: eventwebhook
    steps:
      - name: johns_master_build
        type: Bash
        configuration:
          integrations:
            - name: Creds_DockerRegistry_Punchh
            - name: docker_image_slack_notification
            - name: EnvVars_Development_EventFramework
          inputResources:
            - name: johns_devops_repo
          outputResources:
            - name: johns_docker_image
        execution:
          onStart:
            # - echo $COMPOSE
            # - echo -n $COMPOSE
            - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            - sudo chmod +x /usr/local/bin/docker-compose
            - pushd $res_johns_devops_repo_resourcePath
            - docker-compose up -d es
            - docker-compose up -d mongo
          onExecute:
            - echo "hello"
            - docker ps -a
            - sleep 60
            - docker ps -a

          onSuccess:
            - |
                if ( [ $BRANCH == "master" ] && [ $IS_PULL_REQUEST == false ] )
                then
                  write_output johns_docker_image "imageTag=$COMMIT buildNumber=$runNumber"
                fi

      - name: johns_staging_build
        type: Bash
        configuration:
          environmentVariables:
            PIPELINE_TRIGGER_DETAIL:
              description: "The branch you want to build"
              default: ""
              allowCustom: true
          integrations:
            - name: Creds_DockerRegistry_Punchh
            - name: docker_image_slack_notification
            - name: EnvVars_Development_EventFramework
          inputResources:
            - name: johns_devops_repo
              trigger: false
            - name: johns_docker_image
              trigger: false
        execution:
          onStart:
            - send_notification docker_image_slack_notification "started $step_name"
          onExecute:
            - export BRANCH_NAME="${int_EnvVars_Development_EventFramework_BRANCH_NAME}""
            - pushd ${res_eventframework_code_repo_resourcePath}
            - echo "step 2 branch name :- $BRANCH_NAME"
            - if [[ ${#PIPELINE_TRIGGER_DETAIL} -gt 0 ]]; then export BRANCH_NAME=$PIPELINE_TRIGGER_DETAIL; fi
            - git checkout $BRANCH_NAME
            - docker build -f app/build/Dockerfile -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH_NAME . --pull
            - docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH_NAME
          onComplete:
            - send_notification docker_image_slack_notification "finished $step_name"


